import matplotlib
matplotlib.use("TkAgg")
import pandas as pd
import matplotlib.pyplot as plt
from wordcloud import WordCloud
df = pd.read_csv("data/cleaned_reviews.csv")
plt.figure()
df['rating'].value_counts().sort_index().plot(kind='bar')
plt.title("Rating Distribution")
plt.xlabel("Rating")
plt.ylabel("Count")
plt.show()
plt.figure()
df['sentiment'].value_counts().plot(kind='bar')
plt.title("Sentiment Distribution")
plt.xlabel("Sentiment")
plt.ylabel("Count")
plt.show()
negative_text = " ".join(df[df['sentiment'] == "Negative"]['clean_review'])
wc = WordCloud(background_color="white").generate(negative_text)
plt.figure(figsize=(6, 4))
plt.imshow(wc)
plt.axis("off")
plt.title("Negative Reviews Word Cloud")
plt.show()
plt.figure()
df.groupby('platform')['rating'].mean().plot(kind='bar')
plt.title("Average Rating by Platform")
plt.xlabel("Platform")
plt.ylabel("Average Rating")
plt.show()
plt.figure()
df.groupby('verified_purchase')['rating'].mean().plot(kind='bar')
plt.title("Average Rating: Verified vs Non-Verified Users")
plt.xlabel("Verified Purchase")
plt.ylabel("Average Rating")
plt.show()
top_locations = df['location'].value_counts().head(10).index
plt.figure()
df[df['location'].isin(top_locations)] \
    .groupby('location')['rating'].mean() \
    .plot(kind='bar')
plt.title("Average Rating by Location (Top 10)")
plt.xlabel("Location")
plt.ylabel("Average Rating")
plt.show()
plt.figure()
df.groupby('rating')['review_length'].mean().plot(kind='bar')
plt.title("Average Review Length per Rating")
plt.xlabel("Rating")
plt.ylabel("Review Length")
plt.show()
plt.figure()
df.groupby('version')['rating'].mean().plot(kind='bar')
plt.title("Average Rating by ChatGPT Version")
plt.xlabel("Version")
plt.ylabel("Average Rating")
plt.show()
